name: Backup GitHub repo to s3 bucket

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  backup:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to be backed up
        uses: actions/checkout@v4

      # - name: Dump github context
      #   run:   echo "$GITHUB_CONTEXT"
      #   shell: bash
      #   env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: get repo name
        run: echo "Repo name is $REPO_NAME"

      - name: Mirror repo to s3
        run: git clone --mirror https://github.com/$GITHUB_REPOSITORY

        # git clone --mirror https://github.com/$GITHUB_REPOSITORY
        #   cd $GITHUB_REPOSITORY
        #   git push --mirror s3://$S3_BUCKET/$S3_PREFIX
        # uses: 
        # with:
        #   s3-bucket: 'dirks-bucket-221221'
        #   s3-prefix: 'githubRepoBackup'
        #   s3-region: 'us-east-1'
        #   repository-path: 'repo-to-backup'
      
      - name: tar and compress
        run: tar -czvf $REPO_NAME.tar.gz $REPO_NAME.git

      - name: List directories
        run: ls -ltra