name: Backup GitHub repo to s3 bucket

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  backup:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to be backed up
        uses: actions/checkout@v4

      # - name: Dump github context
      #   run:   echo "$GITHUB_CONTEXT"
      #   shell: bash
      #   env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}

      # - name: get repo name
      #   run: echo "Repo name is $REPO_NAME"

      # - name: Mirror repo to s3
      #   run: git clone --mirror $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
    
      # - name: tar and compress
      #   run: tar -czvf $REPO_NAME.tar.gz $REPO_NAME.git

      # - name: List directories
      #   run: ls -ltra

      - name: Run script
        run: ./backup-repo-to-s3.sh
        env:
          PREFIX: "packer-ansible"
          REPOSITORY_NAME: "packer-ansible-repo"
          BUCKET: "github-backup-S3"
          REPO_NAME: ${{ github.event.repository.name }}